apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-iris-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-iris-app
  template:
    metadata:
      labels:
        app: flask-iris-app
    spec:
      containers:
      - name: flask-iris-app
        image: your-dockerhub-username/flask-iris-app:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"